"""
02_qc_filtering.py
==================

Compute QC metrics on the simulated dataset and filter low-quality cells.

Steps:
    * Load the counts generated by 01_simulate_scrnaseq.py.
    * Compute QC metrics: total counts (n_counts), number of genes (n_genes),
      and percentage of reads in mitochondrial genes (% mitochondrial).
      NOTE: the synthetic data does not model mitochondria explicitly, so we
      *simulate* a plausible mitochondrial fraction (roughly 5-15%) per cell
      in order to demonstrate the standard QC workflow.
    * Filter cells with extreme values (doublets / empty droplets / dead cells):
        - too few counts (empty droplets / dying cells)
        - too few genes
        - too many genes (doublets / multiplets)
        - too high mitochondrial fraction (dead cells)
    * Save the filtered AnnData and QC plots.

Outputs (output/):
    * qc_metrics.csv        - per-cell QC metrics (pre-filter)
    * qc_violin_metrics.png - violin plots of n_counts, n_genes, pct_mito
    * qc_scatter_counts_mito.png - counts vs % mito scatter (pre + post filter)
    * qc_scatter_counts_genes.png - counts vs genes scatter
    * filtered.h5ad         - AnnData after filtering (with cell-type labels kept)
"""

import os

import matplotlib

matplotlib.use("Agg")

import numpy as np
import pandas as pd
import scanpy as sc
from matplotlib import pyplot as plt

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
OUT_DIR = "output"
RAW_FILE = os.path.join(OUT_DIR, "counts_matrix.h5ad")

# QC thresholds (these are sensible defaults; inspect the violin plots first).
MIN_COUNTS = 1000     # remove empty / very low-UMI cells
MAX_COUNTS = 20000    # remove likely doublets (very high UMI)
MIN_GENES = 400       # remove low-complexity cells
MAX_GENES = 4500      # remove likely doublets (very many genes)
MAX_PCT_MITO = 0.18   # remove dead cells (high mito fraction)

SEED = 42
rng = np.random.default_rng(SEED)


def simulate_mitochondrial_fraction(adata):
    """
    Assign a synthetic mitochondrial fraction to each cell.

    Fraction is drawn from a distribution centered around 5-15%, with a small
    population of "dying" cells pushed to very high fractions (so that the
    MAX_PCT_MITO filter removes some cells, demonstrating the workflow).
    """
    n = adata.n_obs
    frac = rng.beta(4.0, 12.0, size=n)          # ~ mean 0.25 -> too high, adjust below
    frac = 0.03 + frac * 0.25                   # spread roughly 3-10%
    # Correlate mito fraction with low library size (dying cells have few counts).
    n_counts = np.asarray(adata.obs["n_counts"]).ravel()
    # A subset flagged as dying cells get a strongly elevated fraction.
    dead = rng.random(n) < 0.05
    frac[dead] = rng.uniform(0.35, 0.6, size=dead.sum())
    # Only put the high fraction on low-count cells for realism.
    low = n_counts < np.percentile(n_counts, 30)
    boost = (rng.random(n) < 0.3) & low
    frac[boost] += rng.uniform(0.1, 0.3, size=boost.sum())
    return np.clip(frac, 0.0, 1.0)


def main():
    print("=" * 70)
    print(" 02_qc_filtering.py — QC metrics & filtering")
    print("=" * 70)
    os.makedirs(OUT_DIR, exist_ok=True)

    print(f"\n[1/4] Loading {RAW_FILE} ...")
    adata = sc.read_h5ad(RAW_FILE)
    print(f"  * loaded: {adata.shape[0]} cells x {adata.shape[1]} genes")

    print("\n[2/4] Computing QC metrics ...")
    adata.obs["n_counts"] = np.asarray(adata.X.sum(axis=1)).ravel()
    adata.obs["n_genes"] = np.asarray((adata.X > 0).sum(axis=1)).ravel()
    # Simulated mitochondrial fraction (see docstring).
    adata.obs["pct_counts_mito"] = simulate_mitochondrial_fraction(adata) * 100.0

    # Save QC metrics table.
    qc_cols = ["n_counts", "n_genes", "pct_counts_mito", "cell_type"]
    adata.obs[qc_cols].to_csv(os.path.join(OUT_DIR, "qc_metrics.csv"))
    print("  * saved -> output/qc_metrics.csv")

    print("\n[3/4] Filtering cells ...")
    before = adata.n_obs
    print(f"  * cells before filtering: {before}")
    sc.pp.filter_cells(adata, min_counts=MIN_COUNTS)
    sc.pp.filter_cells(adata, min_genes=MIN_GENES)
    sc.pp.filter_cells(adata, max_counts=MAX_COUNTS)
    sc.pp.filter_cells(adata, max_genes=MAX_GENES)
    # Filter dead cells by mitochondrial fraction (manual threshold).
    keep_mito = adata.obs["pct_counts_mito"] <= MAX_PCT_MITO * 100.0
    adata = adata[keep_mito].copy()
    after = adata.n_obs
    print(f"  * cells after filtering : {after}  (removed {before - after})")

    print("\n[4/4] Saving & plotting ...")
    adata.write(os.path.join(OUT_DIR, "filtered.h5ad"))
    print("  * saved -> output/filtered.h5ad")

    # ---- Plot 1: violin plots of the three QC metrics ---------------------- #
    metrics = ["n_counts", "n_genes", "pct_counts_mito"]
    titles = ["Total counts (UMIs)", "Genes detected", "% mitochondrial"]
    fig, axes = plt.subplots(1, 3, figsize=(14, 4.5))
    for ax_, key, title in zip(axes, metrics, titles):
        sc.pl.violin(
            adata,
            keys=key,
            jitter=0.4,
            size=0.4,
            show=False,
            ax=ax_,
            rotation=0,
        )
        ax_.set_title(title)
    fig.suptitle("QC metrics after filtering", y=1.02)
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "qc_violin_metrics.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)

    # ---- Plot 2: counts vs % mito (scatter) -------------------------------- #
    fig, ax = plt.subplots(figsize=(6.5, 5))
    sc_ = ax.scatter(
        adata.obs["n_counts"],
        adata.obs["pct_counts_mito"],
        c=adata.obs["n_genes"],
        s=6,
        cmap="viridis",
        alpha=0.6,
    )
    ax.axhline(MAX_PCT_MITO * 100.0, color="red", ls="--", lw=1.2, label="mito threshold")
    ax.set_xlabel("Total counts")
    ax.set_ylabel("% mitochondrial")
    ax.set_title("Counts vs % mitochondrial (post-filter)")
    ax.legend()
    cb = fig.colorbar(sc_, ax=ax)
    cb.set_label("n_genes")
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "qc_scatter_counts_mito.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)

    # ---- Plot 3: counts vs genes (scatter) --------------------------------- #
    fig, ax = plt.subplots(figsize=(6.5, 5))
    ax.scatter(adata.obs["n_counts"], adata.obs["n_genes"], s=6, alpha=0.4, color="#4C72B0")
    ax.set_xlabel("Total counts")
    ax.set_ylabel("Genes detected")
    ax.set_title("Counts vs genes")
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "qc_scatter_counts_genes.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)

    # ---- Plot 4: cell-type composition before/after filtering -------------- #
    fig, ax = plt.subplots(figsize=(7, 4.5))
    (adata.obs["cell_type"].value_counts(normalize=True) * 100).plot.bar(
        ax=ax, color="#55A868", edgecolor="white"
    )
    ax.set_ylabel("% of cells")
    ax.set_title("Cell-type composition after filtering")
    ax.set_ylim(0, 100)
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "qc_celltype_composition.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)

    print("  * saved 4 figures to output/")
    print("\nDone. Run 03_normalize_hvg_pca.py next.\n")


if __name__ == "__main__":
    main()
